import fs from "node:fs/promises";
import path from "node:path";

// Pull a broad set of socials, but keep it practical for the UI.
const SLUGS = [
    "github",
    "linkedin",
    "x",
    "twitter",
    "instagram",
    "facebook",
    "threads",
    "tiktok",
    "youtube",
    "twitch",
    "discord",
    "slack",
    "telegram",
    "whatsapp",
    "signal",
    "snapchat",
    "pinterest",
    "reddit",
    "medium",
    "devdotto",
    "stackoverflow",
    "hashnode",
    "substack",
    "patreon",
    "buymeacoffee",
    "paypal",
    "venmo",
    "cashapp",
    "dribbble",
    "behance",
    "figma",
    "notion",
    "calendly",
    "googlecalendar",
    "spotify",
    "soundcloud",
    "applepodcasts",
    "mastodon",
    "gitlab",
    "bitbucket",
    "codepen",
    "vercel",
    "netlify"
];

function safeJsString(value) {
    return value.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
}

const iconsDir = path.join(process.cwd(), "node_modules", "simple-icons", "icons");

/**
 * Generate a small, browser-friendly dataset by reading SVGs directly.
 * This avoids depending on the JS export surface of `simple-icons`.
 */
const platforms = [];
for (const slug of SLUGS) {
    const svgPath = path.join(iconsDir, `${slug}.svg`);
    let svg;
    try {
        svg = await fs.readFile(svgPath, "utf8");
    } catch {
        continue;
    }

    const titleMatch = svg.match(/<title>([^<]+)<\/title>/i);
    const pathMatch = svg.match(/\sd="([^"]+)"/i);
    if (!pathMatch) continue;

    platforms.push({
        slug,
        title: titleMatch?.[1]?.trim() || slug,
        path: pathMatch[1]
    });
}

platforms.sort((a, b) => a.title.localeCompare(b.title));

const out = `// Generated by scripts/build-icons.mjs
// Do not edit by hand.

export const SOCIAL_PLATFORMS = ${JSON.stringify(
    platforms.map((p) => ({ slug: p.slug, title: p.title })),
    null,
    2
)};

export const SOCIAL_ICON_PATHS = {
${platforms
        .map((p) => `  "${p.slug}": "${safeJsString(p.path)}"`)
        .join(",\n")}
};
`;

const outPath = path.join(process.cwd(), "src", "assets", "social-icons.js");
await fs.writeFile(outPath, out, "utf8");

console.log(`Wrote ${platforms.length} social icons -> ${outPath}`);
